name: List GCP Buckets
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  multi-identity:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'devAuth'
        if: github.ref != 'refs/heads/main'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          workload_identity_provider: 'projects/720003034727/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'bucket-dev@regal-muse-335423.iam.gserviceaccount.com'

      - id: 'prodAuth'
        if: github.ref == 'refs/heads/main'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          workload_identity_provider: 'projects/720003034727/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'bucket-prod@regal-muse-335423.iam.gserviceaccount.com'

      # Install gcloud, automatically picks up authentication from auth.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: listDevBucket
        name: List Content of DevBucket
        #if: github.event_name == 'pull_request'
        run: gcloud storage ls gs://staging.regal-muse-335423.appspot.com
        continue-on-error: true

      - id: listProdBucket
        name: List Content of ProdBucket
        #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: gcloud storage ls gs://regal-muse-335423.appspot.com
        continue-on-error: true
